title: TrueCharts Build Guide
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://jbsoum.github.io/TrueCharts_Build-Guide/

aux_links:
  Powered by TrueCharts: https://truecharts.org/
